cargo-features = ["codegen-backend"]

[package]
name = "bevy-visualgo"
version = "0.1.0"
edition = "2024"

[features]
default = []
dev = ["bevy/dynamic_linking"]

[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
  "std",
  "bevy_log",
  "async_executor",
  "multi_threaded",
  "bevy_state",
  "libm",
  "reflect_documentation",
  "reflect_functions",
  # "serialize",
]

[dependencies]
bevy_ratatui = { version = "0.9.3", features = ["libm"] }
ratatui = "0.29.0"
getrandom = { version = "*", features = ["wasm_js"] }

log = { version = "*", features = [
  "max_level_debug",
  "release_max_level_warn",
] }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
codegen-backend = "llvm"

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
